[package]
name = "toolhub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = "0.11"
image = "0.22"
bardecoder = "0.2.2"